"""add image_key to guestbook

Revision ID: 1db8d979d862
Revises: 3a1b1886c0b9
Create Date: 2026-09-28 01:20:54.532552

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db8d979d862'
down_revision: str | None = '3a1b1886c0b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guestbook', sa.Column('image_key', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guestbook', 'image_key')
    # ### end Alembic commands ###
