"""add post_views table for view dedup

Revision ID: 3a1b1886c0b9
Revises: ceaa1d12dca5
Create Date: 2026-09-24 21:10:02.276581

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1b1886c0b9'
down_revision: str | None = 'ceaa1d12dca5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_views',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('visitor', sa.String(length=32), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'visitor', 'day')
    )
    op.create_index(op.f('ix_post_views_day'), 'post_views', ['day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_views_day'), table_name='post_views')
    op.drop_table('post_views')
    # ### end Alembic commands ###
