"""add game_scores table

Revision ID: 5853c98a9788
Revises: c9ede5faad5b
Create Date: 2026-07-27 23:15:15.926158

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5853c98a9788'
down_revision: str | None = 'c9ede5faad5b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_key', sa.String(length=40), nullable=False),
    sa.Column('player_name', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_scores_game_key'), 'game_scores', ['game_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_scores_game_key'), table_name='game_scores')
    op.drop_table('game_scores')
    # ### end Alembic commands ###
