"""add user session id

Revision ID: 79bb4324bcf8
Revises: 447b9c88149c
Create Date: 2026-09-28 12:00:16.498519

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79bb4324bcf8'
down_revision: str | None = '447b9c88149c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 비워둘 수 있는 칸이라 마이그레이션을 먼저 올려도 옛 코드가 그대로 돈다.
    # 기존 계정은 다음 로그인 때 채워진다.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_id')
    # ### end Alembic commands ###
