"""link comments guestbook game_scores to users

Revision ID: ceaa1d12dca5
Revises: 255064d9f75b
Create Date: 2026-08-01 11:56:00.606803

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceaa1d12dca5'
down_revision: str | None = '255064d9f75b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_foreign_key('fk_comments_user_id_users', 'comments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('game_scores', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.alter_column('game_scores', 'player_name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.create_index(op.f('ix_game_scores_user_id'), 'game_scores', ['user_id'], unique=False)
    op.create_foreign_key('fk_game_scores_user_id_users', 'game_scores', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('guestbook', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_guestbook_user_id'), 'guestbook', ['user_id'], unique=False)
    op.create_foreign_key('fk_guestbook_user_id_users', 'guestbook', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_guestbook_user_id_users', 'guestbook', type_='foreignkey')
    op.drop_index(op.f('ix_guestbook_user_id'), table_name='guestbook')
    op.drop_column('guestbook', 'user_id')
    op.drop_constraint('fk_game_scores_user_id_users', 'game_scores', type_='foreignkey')
    op.drop_index(op.f('ix_game_scores_user_id'), table_name='game_scores')
    op.alter_column('game_scores', 'player_name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.drop_column('game_scores', 'user_id')
    op.drop_constraint('fk_comments_user_id_users', 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
